name: static analysis

on:
  push:
    branches: [main]
  pull_request:

jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, intl
          coverage: none

      - name: Install dependencies
        run: composer update --prefer-dist --no-interaction

      - name: Pint (code style)
        run: composer lint:check

      - name: PHPStan
        run: composer stan
